### ISSUE TITLE
crashes on luanch

### ISSUE THREAD

**Issue by mcbugreporter** [aapelix/BlocksMined#1]
heres the crash report
please fix it i NEED this mod

Uncaught exception in thread "main"
java.lang.RuntimeException: Error creating Mixin config blocksmined.client.mixins.json for mod blocksmined
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:96)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config blocksmined.client.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:168)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:121)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:108)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:98)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:94)
	... 3 more
Caused by: java.lang.IllegalArgumentException: The specified resource 'blocksmined.client.mixins.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1395)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:163)
	... 7 more

**Comment by aapelix** [comment]
I'll try to see what I can do about it when I get back home, so it may take
a while (a couple of days)

**Comment by mcbugreporter** [comment]
kay thanks

**Comment by mcbugreporter** [comment]
i tried to fix it with the source code... but i dont know java

**Comment by aapelix** [comment]
Sorry for making you wait, this should be fixed now. I uploaded a new 1.1.0 version to Modrinth.
